[package]
name = "cs39"
version = "0.1.0"
authors = ["Phoenix Kahlo <kahlo.phoenix@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.3.3"
num_cpus = "1.12.0"
rand = "0.7.3"
byte-unit = "3.0.3"

